name: Maven CI

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GIT_TOKEN }}


      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: |
          cd cli/cli
          mvn package
          cd ../..
          mvn package

      - name: Commit JAR

        run: |
          git config --global user.name "Wdboyes13"
          git config --global user.email "willdev2025@outlook.com"
          git remote set-url origin https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git
          git status
          git add .

          if ! git diff --cached --quiet; then
            git pull
            git commit -m "Auto-build jar"
            git push origin main
          else
            echo "No changes to commit :3"
          fi